### PR TITLE
fix build issue

### PR DESCRIPTION
**Pull request by maximthomas**
fix build issue #19, rename artifacts to `opendientiyplatform` and remove OpenAM submodule

### CODE REVIEW

**Comment by lscorcia** [comment]
Would it be possible to build with Java 11? I tried with your PR and it seems to fail with "version 1.5 no longer supported" in project jee-agents-sdk .

Thank you!

**Comment by lscorcia** [comment]
Additional comment - the newly generated package does not contain the necessary dependencies, so it does not install:

* agent.jar
* commons-io-<version>.jar
* openam-installtools-<version>.jar
* openam-installtools-launcher-<version>.jar
* openssoclientsdk.jar

**Comment by lscorcia** [comment]
Unfortunately even that isn't enough. Now it installs correctly, but it errors at startup. Missing/moved dependency?

14-Sep-2023 17:30:40.080 SEVERE [main] org.apache.tomcat.util.digester.Digester.startElement Begin event threw exception
        java.lang.NoClassDefFoundError: org/forgerock/openam/sdk/org/forgerock/util/time/TimeService
                at org.forgerock.openam.utils.Time.<init>(Time.java:48)
                at org.forgerock.openam.utils.Time.<clinit>(Time.java:43)
                at com.iplanet.am.util.SystemProperties$PropertiesHolder.<init>(SystemProperties.java:751)
                at com.iplanet.am.util.SystemProperties.<clinit>(SystemProperties.java:135)
                at com.sun.identity.agents.arch.AgentConfiguration.bootStrapClientConfiguration(AgentConfiguration.java:708)
                at com.sun.identity.agents.arch.AgentConfiguration.initializeConfiguration(AgentConfiguration.java:1147)
                at com.sun.identity.agents.arch.AgentConfiguration.<clinit>(AgentConfiguration.java:1586)
                at com.sun.identity.agents.arch.Manager.<clinit>(Manager.java:675)
                at com.sun.identity.agents.tomcat.v6.AmTomcatRealm.<clinit>(AmTomcatRealm.java:67)

**Comment by maximthomas** [comment]
@lscorcia hi, you can check the latest commit in the PR

**Pull request merged**
